# Generated by Django 4.2.23 on 2025-08-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0002_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='days',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='states',
            new_name='title',
        ),
        migrations.CreateModel(
            name='DestinationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_details', to='travelers.destination')),
            ],
            options={
                'verbose_name': 'destination detail',
                'verbose_name_plural': 'destination details',
                'db_table': 'destination_detail',
            },
        ),
    ]
