# Generated by Django 4.2.23 on 2025-08-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0003_rename_days_destination_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationdetail',
            options={'ordering': ['-id'], 'verbose_name': 'destination detail', 'verbose_name_plural': 'destination details'},
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('travel_date', models.DateField()),
                ('num_people', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.customer')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.destination')),
            ],
            options={
                'verbose_name': 'booking detail',
                'verbose_name_plural': 'booking details',
                'db_table': 'booking',
                'ordering': ['-id'],
            },
        ),
    ]
