# Generated by Django 4.2.23 on 2025-08-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0006_booking_amount_paid_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('image', models.ImageField(upload_to='spotlight_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TravelersChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('image', models.ImageField(upload_to='travelers_choice/')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TripIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='trip_ideas/')),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_link', models.URLField(blank=True)),
            ],
        ),
    ]
