# Generated by Django 4.2.23 on 2025-08-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0007_spotlight_travelerschoice_tripidea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripIdea',
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('beach', 'Beach Getaway'), ('mountain', 'Mountain Adventure'), ('city', 'City Escape'), ('desert', 'Desert Safari')], default='beach', max_length=20),
        ),
    ]
